[tool.black]
line-length = 88
target-version = ["py39", "py310"]  # Specify your Python versions
include = '\.py$'  # Only include Python files
exclude = '''
/(
    \.git
    | \.hg
    | \.mypy_cache
    | \.tox
    | \.venv
    | _build
    | buck-out
    | build
    | env
    | dist
)/
'''
